package org.ichat.backend.services.account;

import dev.samstevens.totp.exceptions.QrGenerationException;
import org.ichat.backend.model.tables.User;
import org.ichat.backend.model.util.auth.AccountCredentialsDTO;
import org.springframework.lang.NonNull;

/**
 * Service for handling two-factor authentication, it uses the Zxing library for generating QR codes
 */
public interface ITwoFactorAuthService {
    /**
     * Sends a verification code to the user's email address. This is different from the email verification, but uses the same service.
     * @param user The user to send the code to
     * @return A message indicating that the code has been sent
     */
    String requestMfa(User user);

    /**
     * Verifies the MFA code provided by the user.
     *
     * @param credentials The credentials of the user.
     */
    void verifyMFA(User requester, AccountCredentialsDTO credentials);

    /**
     * Generate a new 2FA secret based on the SHA-256 algorithm,
     * with 6 digits and a 30-second period by default (can be changed in the application.yml file)
     * @return the generated secret as a string
     */
    String generateMfaSecret();

    /**
     * Generate a QR code image for the provided secret and email
     * @param secret 2FA secret, normally generated by {@link #generateMfaSecret()}
     * @param email the email of the user
     * @return the generated QR code image as a data URI
     * @throws QrGenerationException if the QR code generation fails
     */
    String generateMfaImage(String secret, String email) throws QrGenerationException;
}
