package org.ichat.backend.services.account;

import dev.samstevens.totp.exceptions.QrGenerationException;
import org.springframework.lang.NonNull;

/**
 * Service for handling two-factor authentication, it uses the Zxing library for generating QR codes
 */
public interface ITwoFactorAuthService {
    /**
     * Check if the provided 2FA code is valid
     * @param secret 2FA secret, normally generated by {@link #generateMfaSecret()}
     * @param provided_code 2FA code provided by the user
     * @return true if the code is valid, false otherwise
     */
    boolean codeIsValid(String secret, @NonNull String provided_code);

    /**
     * Generate a new 2FA secret based on the SHA-256 algorithm,
     * with 6 digits and a 30-second period by default (can be changed in the application.yml file)
     * @return the generated secret as a string
     */
    String generateMfaSecret();

    /**
     * Generate a QR code image for the provided secret and email
     * @param secret 2FA secret, normally generated by {@link #generateMfaSecret()}
     * @param email the email of the user
     * @return the generated QR code image as a data URI
     * @throws QrGenerationException if the QR code generation fails
     */
    String generateMfaImage(String secret, String email) throws QrGenerationException;
}
