steps:
  # Step 1: Build the Docker image using the Containerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/tinypet-404519/linkedout-repo/linkedout', '.']

  # Step 2: Push the image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/tinypet-404519/linkedout-repo/linkedout']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'linkedout'
      - '--image=europe-west1-docker.pkg.dev/tinypet-404519/linkedout-repo/linkedout'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--service-account=owner-318@tinypet-404519.iam.gserviceaccount.com'
      - '--allow-unauthenticated'
      - '--set-secrets=DB_PASS=projects/tinypet-404519/secrets/DB_PASS:latest'
      - '--set-secrets=MAIL_PASS=projects/tinypet-404519/secrets/MAIL_PASS:latest'
      - '--set-secrets=DB_URL=projects/tinypet-404519/secrets/DB_URL:latest'
      - '--set-secrets=GOOGLE_API_KEY=projects/tinypet-404519/secrets/GOOGLE_API_KEY:latest'
      - '--set-secrets=JWT_SECRET=projects/tinypet-404519/secrets/JWT_SECRET:latest'
      - '--set-secrets=OCI_FINGERPRINT=projects/tinypet-404519/secrets/OCI_FINGERPRINT:latest'
      - '--set-secrets=OCI_KEY_B64=projects/tinypet-404519/secrets/OCI_KEY_B64:latest'
      - '--update-env-vars=DB_USER=linkedout,MAIL_USER=yassineyassine333@gmail.com,OCI_TENANCY=ocid1.tenancy.oc1..aaaaaaaaa4whtfd2gnpqw3fg2hcmbzchuljqk4ygzplatmtmsm5p3folyxiq,OCI_USER=ocid1.user.oc1..aaaaaaaanrltas6ynxfmfobvyapd5mxktmeql6qlb6x3uz233kdb6r27extq'

timeout: '1200s'

images:
- 'europe-west1-docker.pkg.dev/tinypet-404519/linkedout-repo/linkedout'
