steps:
  # - name: 'gcr.io/cloud-builders/mvn'
  #   args: ['clean', 'package', '-DskipTests', '-Dspring.profiles.active=prod']
  #   dir: 'backend'

  # Step 2: Build the Docker image using the Containerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/tinypet-404519/linkedout-repo/linkedout', '.']

  # Step 3: Push the image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/tinypet-404519/linkedout-repo/linkedout']

timeout: '1200s'

images:
- 'europe-west1-docker.pkg.dev/tinypet-404519/linkedout-repo/linkedout'
