steps:
  # Step 1: Build the Docker image using the Containerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/linkedout-10/linkedout-repo/linkedout', 'backend/']

  # Step 2: Push the image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/linkedout-10/linkedout-repo/linkedout']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'linkedout'
      - '--image=us-central1-docker.pkg.dev/linkedout-10/linkedout-repo/linkedout'
      - '--region=us-central1'
      - '--platform=managed'
      - '--memory=1Gi'
      - '--allow-unauthenticated'
      - '--min-instances=0'
      - '--max-instances=0'
      - '--concurrency=50'
      - '--set-secrets=DB_PASS=DB_PASS:latest'
      - '--set-secrets=MAIL_PASS=MAIL_PASS:latest'
      - '--set-secrets=DB_URL=DB_URL:latest'
      - '--set-secrets=GOOGLE_API_KEY=GOOGLE_API_KEY:latest'
      - '--set-secrets=JWT_SECRET=JWT_SECRET:latest'
      - '--set-secrets=OCI_FINGERPRINT=OCI_FINGERPRINT:latest'
      - '--set-secrets=OCI_KEY_B64=OCI_KEY_B64:latest'
      - '--set-secrets=MAIL_USER=MAIL_USER:latest'
      - '--set-secrets=OCI_TENANCY=OCI_TENANCY:latest'
      - '--set-secrets=OCI_USER=OCI_USER:latest'
      - '--set-secrets=DB_USER=DB_USER:latest'

timeout: '1200s'
serviceAccount: 'projects/linkedout-10/serviceAccounts/linkedout-backend@linkedout-10.iam.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY
  logStreamingOption: STREAM_ON
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

images:
- 'us-central1-docker.pkg.dev/linkedout-10/linkedout-repo/linkedout'
