version: '3.8'

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  spring-app:
    image: ${DOCKER_USERNAME}/spring-app:latest
    ports:
      - "8080:8080"
    environment:
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
    depends_on:
      - postgres

  angular-app:
    image: ${DOCKER_USERNAME}/angular-app:latest
    ports:
      - "4200:4200"
    depends_on:
      - spring-app

volumes:
  postgres-data:
