version: '3'

services:
  postgres:
    image: postgres:alpine
    networks:
      - postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: securecapita
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: yassineder/backend:latest
    networks:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_URL: jdbc:postgresql://postgres:5432/securecapita
      FRONTEND_URL: https://frontend:443
      MAIL_USER: $MAIL_USER
      MAIL_PASS: $MAIL_PASS
      JWT_SECRET: $JWT_SECRET
      RECAPTCHA_SECRET: $RECAPTCHA_SECRET
      GOOGLE_API_KEY: $GOOGLE_API_KEY
      GOOGLE_CX: $GOOGLE_CX
    depends_on:
      - postgres

  frontend:
    image: yassineder/frontend:latest
    networks:
      - postgres
    volumes:
      - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

networks:
  postgres:
    driver: bridge

volumes:
  postgres-data:
    driver: local
