spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    timeout: 25
    from: no-reply@linkedout.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true

server:
  port: 8081
security:
  allowed-origins: http://localhost:4200

