spring:
  application:
    name: LinkedOut
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/securecapita
    username: ${DB_USER}
    password: ${DB_PASS}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    timeout: 25
    from: no-reply@linkedout.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        jdbc:
          lob:
            non_contextual_creation: true
          id:
            new_generator_mappings: true
    open-in-view: false
  sql:
    init:
      mode: embedded
  caching:
    user:
      images: 10800000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# Two-factor authentication configuration
totp:
  secret:
    length: 64
  time:
    period: 30

admin:
  secret: 696969

