spring:
  frontend:
    url: ${FRONTEND_URL}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    timeout: 15
    from: no-reply@linkedout.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  ssl:
    key-store: file:/app/backend.p12
    key-alias: backend
    key-store-type: pkcs12
    key-store-password: messi203
    key-password: messi203
    enabled-protocols: TLSv1.2,TLSv1.3
