spring:
  frontend:
    url: ${FRONTEND_URL}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    timeout: 15
    from: no-reply@linkedout.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  ssl:
    key-store: file:/home/ubuntu/linkedout/ssl/springboot.p12
    key-alias: springboot
    key-store-type: pkcs12
    key-store-password: ${KEY_STORE_PASS}
    key-password: ${KEY_STORE_PASS}
