spring:
#  profiles:
#    active: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securecapita
    username: root
    password:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: cb741e46f78fdb
    password: 1b1f80ae697461
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        jdbc:
          lob:
            non_contextual_creation: true
          id:
            new_generator_mappings: true
    open-in-view: false
  sql:
    init:
      mode: embedded
