spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    timeout: 15
    from: no-reply@linkedout.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  ssl:
    key-store-type: PKCS12
    key-store: file:/app/keystore.p12
    key-store-password: ${KEYSTORE_PASS}
    key-alias: tomcat

