spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: LinkedOut
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        jdbc:
          lob:
            non_contextual_creation: true
          id:
            new_generator_mappings: true
        default_schema: public
    open-in-view: true
  sql:
    init:
      mode: embedded
  caching:
    user:
      images: 10800000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jta:
    enabled: true
# Two-factor authentication configuration
totp:
  secret:
    length: 64
  time:
    period: 30

resilience4j:
  ratelimiter:
    instances:
        default:
            limitForPeriod: 10
            limitRefreshPeriod: 10s
            timeoutDuration: 20s
            register-health-indicator: true
            eventConsumerBufferSize: 100


