server:
  port: ${PORT}
  error:
    whitelabel:
      enabled: false
  tomcat:
    connection-timeout: 10000
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    timeout: 15
    from: no-reply@linkedout.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
security:
  allowed-origins: https://yassineder.github.io
