spring:
  frontend:
    url: ${FRONTEND_URL}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    timeout: 15
    from: no-reply@linkedout.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  ssl:
    certificate-private-key: file:/app/privkey.key
    certificate: file:/app/fullchain.crt

