spring:
  application:
    name: securecapita
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/securecapita?createDatabaseIfNotExist=true
    username: root
    password:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 1761a535b5e9ea
    password: 262f7d4dc51961
    timeout: 25
    from: no-reply@securecapita.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        jdbc:
          lob:
            non_contextual_creation: true
          id:
            new_generator_mappings: true
    open-in-view: false
  sql:
    init:
      mode: embedded
  caching:
    user:
      images: 10800000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# Two-factor authentication configuration
totp:
  secret:
    length: 64
  time:
    period: 30

# Links configuration for email verification and password reset services
links:
  verification: /api/auth/verify/
admin:
  secret: 696969

