server:
  port: ${PORT:8080}
  error:
    whitelabel:
      enabled: false
  tomcat:
    connection-timeout: 10000
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    timeout: 15
    from: no-reply@linkedout.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    hibernate:
      ddl-auto: create-drop
security:
  allowed-origins: https://yassineder.github.io

logging:
  level:
    root: INFO
    org.ichat: ERROR  # Adjust package to your app
  google:
    cloud:
      logging:
        enabled: true  # Enable Google Cloud Logging in production
        flushIntervalSeconds: 1  # Optional: flush logs quickly for debugging
