name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Set up Java 19
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '19'

    - name: Copy docker-compose.yml to VM
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.VM_HOST }}
        local: 'docker/docker-compose.yml'
        username: ${{ secrets.VM_USER }}
        remote: '/home/${{ secrets.VM_USER }}/linkedout/docker-compose.yml'
        privateKey: ${{ secrets.SSH_PRIVATE }}

    - name: Deploying Postgres database container
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_PRIVATE }}
        script: |
          cd ~/linkedout
          sudo docker compose -f docker-compose.yml down
          sudo docker compose -f docker-compose.yml up -d

    - name: Build and deploy the application
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "linkedout"
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        appdir: "backend"
        stack: "heroku-22"
        buildpack: "https://github.com/heroku/heroku-buildpack-java.git"