name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker images
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./backend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend

    - name: Push Docker images
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Copy docker-compose.yml to VM
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.VM_HOST }}
        local: 'docker/docker-compose.yml'
        username: ${{ secrets.VM_USER }}
        remote: '/home/${{ secrets.VM_USER }}/linkedout/docker-compose.yml'
        privateKey: ${{ secrets.SSH_PRIVATE }}

    - name: Deploying to remote VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_PRIVATE }}
        script: |
          cd ~/linkedout
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          sudo docker-compose -f docker-compose.yml down
          sudo docker-compose -f docker-compose.yml up -d
