name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Set up Java 19
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '19'

    - name: Copy docker-compose.yml to VM
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.VM_HOST }}
        local: 'docker/docker-compose.yml'
        username: ${{ secrets.VM_USER }}
        remote: '/home/${{ secrets.VM_USER }}/linkedout/docker-compose.yml'
        privateKey: ${{ secrets.SSH_PRIVATE }}

    - name: Deploying Postgres database container
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_PRIVATE }}
        script: |
          cd ~/linkedout
          sudo docker compose -f docker-compose.yml down
          sudo docker compose -f docker-compose.yml up -d

    - name: Build and deploy the application
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        git remote add heroku https://git.heroku.com/linkedout.git
        git subtree push --prefix backend heroku main