name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        distribution: 'oracle'
        java-version: '19'
        cache: 'maven'

    - name: Build Spring Boot application
      run: ./mvnw clean package -DskipTests -Dspring-boot.run.profiles=prod

    - name: Build Angular application
      run: npm install && npm run build

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker images
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-app ./backend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/angular-app ./frontend

    - name: Push Docker images
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/spring-app
        docker push ${{ secrets.DOCKER_USERNAME }}/angular-app

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH to VM and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker yassineder/spring-app
          docker yassineder/angular-app
          docker stop spring-app || true
          docker stop angular-app || true
          docker rm spring-app || true
          docker rm angular-app || true
          docker run -d --name spring-app --env-file ~/linkedout/.env -p 8080:8080 yassineder/spring-app
          docker run -d --name angular-app -p 4200:4200 yassineder/angular-app
